//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogloszenia_Studenckie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obserwacja
    {
        public int ID_Obserwacja { get; set; }
        public int ID_Konto { get; set; }
        public int ID_Ogloszenie { get; set; }
    
        public virtual Konto Konto { get; set; }
        public virtual Ogloszenie Ogloszenie { get; set; }
    }
}
