//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogloszenia_Studenckie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogloszenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogloszenie()
        {
            this.Obserwacja = new HashSet<Obserwacja>();
        }
    
        public int ID_Ogloszenie { get; set; }
        public string Tytul { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> Data_Zamkniecia { get; set; }
        public System.DateTime Data_Zamieszczenia { get; set; }
        public int ID_Kategoria { get; set; }
        public int ID_Konto { get; set; }
        public int ID_Miasto { get; set; }
        public Nullable<int> ID_Uczelnia { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        public virtual Konto Konto { get; set; }
        public virtual Miasto Miasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obserwacja> Obserwacja { get; set; }
        public virtual Uczelnia Uczelnia { get; set; }
    }
}
