//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogloszenia_Studenckie.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Aplikacje_InternetoweEntities : DbContext
    {
        public Aplikacje_InternetoweEntities()
            : base("name=Aplikacje_InternetoweEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<Konto> Konto { get; set; }
        public virtual DbSet<Miasto> Miasto { get; set; }
        public virtual DbSet<Obserwacja> Obserwacja { get; set; }
        public virtual DbSet<Ogloszenie> Ogloszenie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uczelnia> Uczelnia { get; set; }
    }
}
